# Generated by Django 4.2.6 on 2023-10-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('number_plate', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Vehicule',
                'verbose_name_plural': 'Vehicules',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('kilometers', models.IntegerField()),
                ('profile', models.CharField(max_length=50)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.vehicule')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
            },
        ),
        migrations.CreateModel(
            name='FullTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('liters', models.FloatField()),
                ('kilometers', models.IntegerField()),
                ('profile', models.CharField(max_length=50)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.vehicule')),
            ],
            options={
                'verbose_name': 'FullTank',
                'verbose_name_plural': 'FullTanks',
            },
        ),
    ]
